name: daily-monitoring
on:
    schedule:
      # 주중 오전 11시에 실행
        - cron: '0 2 * * 1-5'
jobs:
    monitoring_by_schedule:
        runs-on: ubuntu-latest
        permissions:
          issues: write
        steps:
            - name: 저장소 체크아웃
              uses: actions/checkout@v4

            - name: 파이썬 셋업
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
                
            - name: 의존성 설치
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
          
            - name: 모니터링 실행
              env:
                assets: ${{ vars.assets }}
                periods: ${{ vars.periods }}
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
                GH_OWNER: ${{ github.repository_owner }}
                GH_REPO: ${{ github.event.repository.name }}
              run: python main.py